/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ServicesWellnessRouteImport } from './routes/services.wellness'
import { Route as ServicesLandscapingRouteImport } from './routes/services.landscaping'
import { Route as ServicesIndoorRouteImport } from './routes/services.indoor'
import { Route as ServicesBalconyRouteImport } from './routes/services.balcony'
import { Route as DashboardWishlistRouteImport } from './routes/dashboard.wishlist'
import { Route as DashboardWellnessRouteImport } from './routes/dashboard.wellness'
import { Route as DashboardSupportRouteImport } from './routes/dashboard.support'
import { Route as DashboardReviewsRouteImport } from './routes/dashboard.reviews'
import { Route as DashboardReferRouteImport } from './routes/dashboard.refer'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardPaymentsRouteImport } from './routes/dashboard.payments'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard.notifications'
import { Route as DashboardMaintenanceRouteImport } from './routes/dashboard.maintenance'
import { Route as DashboardLibraryRouteImport } from './routes/dashboard.library'
import { Route as DashboardBookingsRouteImport } from './routes/dashboard.bookings'
import { Route as DashboardBookRouteImport } from './routes/dashboard.book'
import { Route as AdminWellnessRouteImport } from './routes/admin.wellness'
import { Route as AdminTestimonialsRouteImport } from './routes/admin.testimonials'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminProjectsRouteImport } from './routes/admin.projects'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminPackagesRouteImport } from './routes/admin.packages'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminInventoryRouteImport } from './routes/admin.inventory'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminCouponsRouteImport } from './routes/admin.coupons'
import { Route as AdminConsultationsRouteImport } from './routes/admin.consultations'
import { Route as AdminCmsRouteImport } from './routes/admin.cms'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ServicesWellnessRoute = ServicesWellnessRouteImport.update({
  id: '/wellness',
  path: '/wellness',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesLandscapingRoute = ServicesLandscapingRouteImport.update({
  id: '/landscaping',
  path: '/landscaping',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesIndoorRoute = ServicesIndoorRouteImport.update({
  id: '/indoor',
  path: '/indoor',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesBalconyRoute = ServicesBalconyRouteImport.update({
  id: '/balcony',
  path: '/balcony',
  getParentRoute: () => ServicesRoute,
} as any)
const DashboardWishlistRoute = DashboardWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWellnessRoute = DashboardWellnessRouteImport.update({
  id: '/wellness',
  path: '/wellness',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSupportRoute = DashboardSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReviewsRoute = DashboardReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReferRoute = DashboardReferRouteImport.update({
  id: '/refer',
  path: '/refer',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPaymentsRoute = DashboardPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMaintenanceRoute = DashboardMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLibraryRoute = DashboardLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBookingsRoute = DashboardBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBookRoute = DashboardBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminWellnessRoute = AdminWellnessRouteImport.update({
  id: '/wellness',
  path: '/wellness',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPackagesRoute = AdminPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConsultationsRoute = AdminConsultationsRouteImport.update({
  id: '/consultations',
  path: '/consultations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCmsRoute = AdminCmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRouteWithChildren
  '/admin/blog': typeof AdminBlogRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/consultations': typeof AdminConsultationsRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/wellness': typeof AdminWellnessRoute
  '/dashboard/book': typeof DashboardBookRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/library': typeof DashboardLibraryRoute
  '/dashboard/maintenance': typeof DashboardMaintenanceRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/refer': typeof DashboardReferRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/wellness': typeof DashboardWellnessRoute
  '/dashboard/wishlist': typeof DashboardWishlistRoute
  '/services/balcony': typeof ServicesBalconyRoute
  '/services/indoor': typeof ServicesIndoorRoute
  '/services/landscaping': typeof ServicesLandscapingRoute
  '/services/wellness': typeof ServicesWellnessRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRouteWithChildren
  '/admin/blog': typeof AdminBlogRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/consultations': typeof AdminConsultationsRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/wellness': typeof AdminWellnessRoute
  '/dashboard/book': typeof DashboardBookRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/library': typeof DashboardLibraryRoute
  '/dashboard/maintenance': typeof DashboardMaintenanceRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/refer': typeof DashboardReferRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/wellness': typeof DashboardWellnessRoute
  '/dashboard/wishlist': typeof DashboardWishlistRoute
  '/services/balcony': typeof ServicesBalconyRoute
  '/services/indoor': typeof ServicesIndoorRoute
  '/services/landscaping': typeof ServicesLandscapingRoute
  '/services/wellness': typeof ServicesWellnessRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRouteWithChildren
  '/admin/blog': typeof AdminBlogRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/consultations': typeof AdminConsultationsRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/wellness': typeof AdminWellnessRoute
  '/dashboard/book': typeof DashboardBookRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/library': typeof DashboardLibraryRoute
  '/dashboard/maintenance': typeof DashboardMaintenanceRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/refer': typeof DashboardReferRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/wellness': typeof DashboardWellnessRoute
  '/dashboard/wishlist': typeof DashboardWishlistRoute
  '/services/balcony': typeof ServicesBalconyRoute
  '/services/indoor': typeof ServicesIndoorRoute
  '/services/landscaping': typeof ServicesLandscapingRoute
  '/services/wellness': typeof ServicesWellnessRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/dashboard'
    | '/gallery'
    | '/login'
    | '/maintenance'
    | '/register'
    | '/services'
    | '/admin/blog'
    | '/admin/bookings'
    | '/admin/cms'
    | '/admin/consultations'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/gallery'
    | '/admin/inventory'
    | '/admin/leads'
    | '/admin/notifications'
    | '/admin/packages'
    | '/admin/payments'
    | '/admin/projects'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/subscriptions'
    | '/admin/testimonials'
    | '/admin/wellness'
    | '/dashboard/book'
    | '/dashboard/bookings'
    | '/dashboard/library'
    | '/dashboard/maintenance'
    | '/dashboard/notifications'
    | '/dashboard/payments'
    | '/dashboard/profile'
    | '/dashboard/refer'
    | '/dashboard/reviews'
    | '/dashboard/support'
    | '/dashboard/wellness'
    | '/dashboard/wishlist'
    | '/services/balcony'
    | '/services/indoor'
    | '/services/landscaping'
    | '/services/wellness'
    | '/admin/'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/login'
    | '/maintenance'
    | '/register'
    | '/services'
    | '/admin/blog'
    | '/admin/bookings'
    | '/admin/cms'
    | '/admin/consultations'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/gallery'
    | '/admin/inventory'
    | '/admin/leads'
    | '/admin/notifications'
    | '/admin/packages'
    | '/admin/payments'
    | '/admin/projects'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/subscriptions'
    | '/admin/testimonials'
    | '/admin/wellness'
    | '/dashboard/book'
    | '/dashboard/bookings'
    | '/dashboard/library'
    | '/dashboard/maintenance'
    | '/dashboard/notifications'
    | '/dashboard/payments'
    | '/dashboard/profile'
    | '/dashboard/refer'
    | '/dashboard/reviews'
    | '/dashboard/support'
    | '/dashboard/wellness'
    | '/dashboard/wishlist'
    | '/services/balcony'
    | '/services/indoor'
    | '/services/landscaping'
    | '/services/wellness'
    | '/admin'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/dashboard'
    | '/gallery'
    | '/login'
    | '/maintenance'
    | '/register'
    | '/services'
    | '/admin/blog'
    | '/admin/bookings'
    | '/admin/cms'
    | '/admin/consultations'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/gallery'
    | '/admin/inventory'
    | '/admin/leads'
    | '/admin/notifications'
    | '/admin/packages'
    | '/admin/payments'
    | '/admin/projects'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/subscriptions'
    | '/admin/testimonials'
    | '/admin/wellness'
    | '/dashboard/book'
    | '/dashboard/bookings'
    | '/dashboard/library'
    | '/dashboard/maintenance'
    | '/dashboard/notifications'
    | '/dashboard/payments'
    | '/dashboard/profile'
    | '/dashboard/refer'
    | '/dashboard/reviews'
    | '/dashboard/support'
    | '/dashboard/wellness'
    | '/dashboard/wishlist'
    | '/services/balcony'
    | '/services/indoor'
    | '/services/landscaping'
    | '/services/wellness'
    | '/admin/'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  GalleryRoute: typeof GalleryRoute
  LoginRoute: typeof LoginRoute
  MaintenanceRoute: typeof MaintenanceRoute
  RegisterRoute: typeof RegisterRoute
  ServicesRoute: typeof ServicesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/services/wellness': {
      id: '/services/wellness'
      path: '/wellness'
      fullPath: '/services/wellness'
      preLoaderRoute: typeof ServicesWellnessRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/landscaping': {
      id: '/services/landscaping'
      path: '/landscaping'
      fullPath: '/services/landscaping'
      preLoaderRoute: typeof ServicesLandscapingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/indoor': {
      id: '/services/indoor'
      path: '/indoor'
      fullPath: '/services/indoor'
      preLoaderRoute: typeof ServicesIndoorRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/balcony': {
      id: '/services/balcony'
      path: '/balcony'
      fullPath: '/services/balcony'
      preLoaderRoute: typeof ServicesBalconyRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/dashboard/wishlist': {
      id: '/dashboard/wishlist'
      path: '/wishlist'
      fullPath: '/dashboard/wishlist'
      preLoaderRoute: typeof DashboardWishlistRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/wellness': {
      id: '/dashboard/wellness'
      path: '/wellness'
      fullPath: '/dashboard/wellness'
      preLoaderRoute: typeof DashboardWellnessRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/support': {
      id: '/dashboard/support'
      path: '/support'
      fullPath: '/dashboard/support'
      preLoaderRoute: typeof DashboardSupportRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reviews': {
      id: '/dashboard/reviews'
      path: '/reviews'
      fullPath: '/dashboard/reviews'
      preLoaderRoute: typeof DashboardReviewsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/refer': {
      id: '/dashboard/refer'
      path: '/refer'
      fullPath: '/dashboard/refer'
      preLoaderRoute: typeof DashboardReferRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/payments': {
      id: '/dashboard/payments'
      path: '/payments'
      fullPath: '/dashboard/payments'
      preLoaderRoute: typeof DashboardPaymentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/maintenance': {
      id: '/dashboard/maintenance'
      path: '/maintenance'
      fullPath: '/dashboard/maintenance'
      preLoaderRoute: typeof DashboardMaintenanceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/library': {
      id: '/dashboard/library'
      path: '/library'
      fullPath: '/dashboard/library'
      preLoaderRoute: typeof DashboardLibraryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/bookings': {
      id: '/dashboard/bookings'
      path: '/bookings'
      fullPath: '/dashboard/bookings'
      preLoaderRoute: typeof DashboardBookingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/book': {
      id: '/dashboard/book'
      path: '/book'
      fullPath: '/dashboard/book'
      preLoaderRoute: typeof DashboardBookRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/wellness': {
      id: '/admin/wellness'
      path: '/wellness'
      fullPath: '/admin/wellness'
      preLoaderRoute: typeof AdminWellnessRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/packages': {
      id: '/admin/packages'
      path: '/packages'
      fullPath: '/admin/packages'
      preLoaderRoute: typeof AdminPackagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/consultations': {
      id: '/admin/consultations'
      path: '/consultations'
      fullPath: '/admin/consultations'
      preLoaderRoute: typeof AdminConsultationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms': {
      id: '/admin/cms'
      path: '/cms'
      fullPath: '/admin/cms'
      preLoaderRoute: typeof AdminCmsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBlogRoute: typeof AdminBlogRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminCmsRoute: typeof AdminCmsRoute
  AdminConsultationsRoute: typeof AdminConsultationsRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPackagesRoute: typeof AdminPackagesRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminWellnessRoute: typeof AdminWellnessRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBlogRoute: AdminBlogRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminCmsRoute: AdminCmsRoute,
  AdminConsultationsRoute: AdminConsultationsRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPackagesRoute: AdminPackagesRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminWellnessRoute: AdminWellnessRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardBookRoute: typeof DashboardBookRoute
  DashboardBookingsRoute: typeof DashboardBookingsRoute
  DashboardLibraryRoute: typeof DashboardLibraryRoute
  DashboardMaintenanceRoute: typeof DashboardMaintenanceRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardPaymentsRoute: typeof DashboardPaymentsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardReferRoute: typeof DashboardReferRoute
  DashboardReviewsRoute: typeof DashboardReviewsRoute
  DashboardSupportRoute: typeof DashboardSupportRoute
  DashboardWellnessRoute: typeof DashboardWellnessRoute
  DashboardWishlistRoute: typeof DashboardWishlistRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBookRoute: DashboardBookRoute,
  DashboardBookingsRoute: DashboardBookingsRoute,
  DashboardLibraryRoute: DashboardLibraryRoute,
  DashboardMaintenanceRoute: DashboardMaintenanceRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardPaymentsRoute: DashboardPaymentsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardReferRoute: DashboardReferRoute,
  DashboardReviewsRoute: DashboardReviewsRoute,
  DashboardSupportRoute: DashboardSupportRoute,
  DashboardWellnessRoute: DashboardWellnessRoute,
  DashboardWishlistRoute: DashboardWishlistRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ServicesRouteChildren {
  ServicesBalconyRoute: typeof ServicesBalconyRoute
  ServicesIndoorRoute: typeof ServicesIndoorRoute
  ServicesLandscapingRoute: typeof ServicesLandscapingRoute
  ServicesWellnessRoute: typeof ServicesWellnessRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesBalconyRoute: ServicesBalconyRoute,
  ServicesIndoorRoute: ServicesIndoorRoute,
  ServicesLandscapingRoute: ServicesLandscapingRoute,
  ServicesWellnessRoute: ServicesWellnessRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  GalleryRoute: GalleryRoute,
  LoginRoute: LoginRoute,
  MaintenanceRoute: MaintenanceRoute,
  RegisterRoute: RegisterRoute,
  ServicesRoute: ServicesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
